import type { Metadata } from "next";
import ThemeToggle from "@/components/ThemeToggle";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-50 dark:bg-gray-900 text-gray-900 dark:text-gray-100">

  <nav className="sticky top-0 z-50 bg-white/80 backdrop-blur border-b">
  
  <div className="max-w-7xl mx-auto px-6 py-4 flex justify-between items-center">

    <h1 className="text-xl font-bold tracking-tight">
      🎬 MovieDB
    </h1>

    <div className="flex gap-6 text-sm font-medium">
      <Link href="/">Home</Link>
      <Link href="/movies">Movies</Link>
      <ThemeToggle />
    </div>

  </div>
</nav>


  {children}
  <footer className="mt-16 border-t py-6 text-center text-sm text-gray-500">
  Built with ❤️ using Next.js & TMDB API
</footer>

</body>
    </html>
  );
}
